name: Hardhat - Linters and Prettier

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x, 21.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: hardhat
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: hardhat/package-lock.json
    - run: npm install

    - run: npx eslint '**/*.{js,ts}'
    - run: npx solhint 'contracts/**/*.sol'
    - run: npx prettier '**/*.{json,sol,md}' --check
